/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
	skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
	skycons.add("day1", Skycons.CLEAR_DAY);
	skycons.add("day2", Skycons.CLOUDY);
	skycons.add("day3", Skycons.PARTLY_CLOUDY_NIGHT);
	skycons.play();
  
$.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22taipei%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
	console.log (data) ;
	var currentTemperature = data.query.results.channel.item.condition.temp  ;
	var tem=parseInt((parseInt(currentTemperature, 10)+40)/1.8-40,10);
	$(".temperature").text(tem);
	$(".date").text(data.query.results.channel.item.condition.date+':');
	$("#now").text(data.query.results.channel.item.condition.text);
	$("#nextday").text(data.query.results.channel.item.forecast[1].date);
    $("#twoday").text(data.query.results.channel.item.forecast[2].date);
    $("#threeday").text(data.query.results.channel.item.forecast[3].date);
	var hightem=data.query.results.channel.item.forecast[1].high;
	var lowtem=data.query.results.channel.item.forecast[1].low;
	var high=parseInt((parseInt(hightem, 10)+40)/1.8-40,10);
	var low=parseInt((parseInt(lowtem, 10)+40)/1.8-40,10);
	$("#nexttem").text(low+ "-" + high);
	var hightem=data.query.results.channel.item.forecast[2].high;
	var lowtem=data.query.results.channel.item.forecast[2].low;
	var high=parseInt((parseInt(hightem, 10)+40)/1.8-40,10);
	var low=parseInt((parseInt(lowtem, 10)+40)/1.8-40,10);
	$("#twotem").text(low+ "-" + high);
	var hightem=data.query.results.channel.item.forecast[3].high;
	var lowtem=data.query.results.channel.item.forecast[3].low;
	var high=parseInt((parseInt(hightem, 10)+40)/1.8-40,10);
	var low=parseInt((parseInt(lowtem, 10)+40)/1.8-40,10);
	$("#threetem").text(low+ "-" + high);
	skycons.set("today", getCode(data.query.results.channel.item.forecast[0].code));
    skycons.set("day1", getCode(data.query.results.channel.item.forecast[1].code));
    skycons.set("day2", getCode(data.query.results.channel.item.forecast[2].code));
    skycons.set("day3", getCode(data.query.results.channel.item.forecast[3].code));
})
  function getCode(code) {
	  if(parseInt(code)>=0&&parseInt(code)<=2)
		  return Skycons.WIND;
	  else if(parseInt(code)>=3&&parseInt(code)<=12)
		  return Skycons.RAIN;
	  else if(parseInt(code)>=13&&parseInt(code)<=17)
		  return Skycons.SNOW;
	  else if(parseInt(code)>=18&&parseInt(code)<=22)
		  return Skycons.FOG;
	  else if(parseInt(code)>=23&&parseInt(code)<=25)
		  return Skycons.WIND;
	  else if(parseInt(code)>=26&&parseInt(code)<=30||parseInt(code)==44)
	  {
		  if(parseInt(code)%2==0)
			  return Skycons.PARTLY_CLOUDY_DAY;
		  else
			  return Skycons.PARTLY_CLOUDY_NIGHT;
	  }
	  else if(parseInt(code)>=31&&parseInt(code)<=36)
	  {
		  if(parseInt(code)%2==0)
			  return Skycons.CLEAR_DAY;
		  else
			  return Skycons.CLEAR_NIGHT;
	  }
	  else if(parseInt(code)>=37&&parseInt(code)<=40)
		  return Skycons.RAIN;
	  else if(parseInt(code)>=41&&parseInt(code)<=43)
		  return Skycons.SNOW;
	  else if(parseInt(code)>=45&&parseInt(code)<=47)
		  return Skycons.RAIN;
}
var place=["臺北市", "新北市", "台中市","臺南市","高雄市","基隆市","桃園市","新竹市","新竹縣","苗栗縣","彰化縣","南投縣","雲林縣","嘉義市","嘉義縣","屏東縣","宜蘭縣","花蓮縣","台東縣","澎湖縣","金門縣","連江縣"];
var ctem=[];
for(i=0;i<22;i++)
{
	$.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+place[i]+"taipei%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
	console.log (data) ;
	var currentTemperature = data.query.results.channel.item.condition.temp  ;
	ctem[i]=parseInt((parseInt(currentTemperature, 10)+40)/1.8-40,10);
	$("#ctem+i").text(ctem[i]);
})
}
$('#dropdown li').on('click', function(){
    alert($(this).text());
});